### ISSUE TITLE
Failing to Initialize Project

### ISSUE THREAD

**Issue by jcrubino** [theduke/django-kickstart#1]
```
Creating development sqlite database and running south migrations...
Traceback (most recent call last):
  File "/home/main/tmp/test/myapp/app/manage.py", line 20, in <module>
    execute_from_command_line(sys.argv)
  File "/home/main/.virtenvs/test/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/main/.virtenvs/test/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/main/.virtenvs/test/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 261, in fetch_command
    commands = get_commands()
  File "/home/main/.virtenvs/test/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 107, in get_commands
    apps = settings.INSTALLED_APPS
  File "/home/main/.virtenvs/test/local/lib/python2.7/site-packages/django/conf/__init__.py", line 54, in __getattr__
    self._setup(name)
  File "/home/main/.virtenvs/test/local/lib/python2.7/site-packages/django/conf/__init__.py", line 50, in _setup
    self._configure_logging()
  File "/home/main/.virtenvs/test/local/lib/python2.7/site-packages/django/conf/__init__.py", line 80, in _configure_logging
    logging_config_func(self.LOGGING)
  File "/usr/lib/python2.7/logging/config.py", line 777, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 575, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler 'console': Unable to set formatter 'simple': 'simple'
Error: could not run manage.py syncdb!
```

**Comment by theduke** [comment]
Fixed, i'm releasing version 0.1.1 to pypi right now.
