### ISSUE TITLE
site_packages_dir - TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by michaelsstuff** [theduke/django-kickstart#4]
Hi,

I was not able to get it running. Any hinits what I need to look for?

```
15:14 $ django-kickstart kick
Checking requirements...
Creating project kick
Creating new project with django-admin.py...
Creating new custom virtualenv...
Traceback (most recent call last):
  File "/usr/bin/django-kickstart", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/django_kickstart/cli.py", line 298, in main
    cli.run()
  File "/usr/lib/python3.4/site-packages/django_kickstart/cli.py", line 64, in run
    self.create(args)
  File "/usr/lib/python3.4/site-packages/django_kickstart/cli.py", line 269, in create
    self.update_sitepackage_settings(venv, settings_path, args)
  File "/usr/lib/python3.4/site-packages/django_kickstart/cli.py", line 197, in update_sitepackage_settings
    site_packages_dir = site_packages_dir.replace("\n", "").replace(virtualenv_path + '/', "")
TypeError: 'str' does not support the buffer interface

```

**Comment by theduke** [comment]
Hey, I haven't touched this code in years...

The error looks like a python 3 compatability issue, at first glance.

**Comment by michaelsstuff** [comment]
Haha, yeah I should have checked the last commit beforehand :-D
And yes I am using python3 so that's probably the problem. 
Thanks anyway for the instant reply.
